spring.application.name=ecommerce-api
spring.security.user.name=admin
spring.security.user.password=1234


server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/eCommerce
spring.datasource.username=postgres
spring.datasource.password=2288